### ISSUE TITLE
Take in account VSCODE_PORTABLE environment variable

### ISSUE THREAD

**Issue by Lassebq** [swsnr/gnome-search-providers-vscode#47]
When VSCODE_PORTABLE is set vscode does not use directory located in `$XDG_CONFIG_HOME`, instead it's using `$VSCODE_PORTABLE/user-data`
![image](https://github.com/swsnr/gnome-search-providers-vscode/assets/68742864/94999529-3913-4a15-87c5-514d8ffaaf87)

**Comment by swsnr** [comment]
I don't use this feature, so I won't add this myself, and am closing this issue because it's not actionable to me.

Pull request are welcome, however.
