### ISSUE TITLE
How do I Uninstall It?

### ISSUE THREAD

**Issue by ulville** [swsnr/gnome-search-providers-vscode#49]
I think removing the uninstall target from the makefile in  bf45b6a15da6ca155b79928ada8d7179696cc575 was a regression. At least until there is a better way. Yes make is not a package manager but it's not an unusual thing to include an uninstall target in the makefile. Especially when there is little to no package managers distributing it. Even so, for people who install it by compiling from this repo (which is the only way to install it for most people rn), make is a nice way to install/uninstall things.

Also I think there is an ethical or philosophical side of it. If you let people install it using Make, I think you should also let them uninstall it using Make. Or at least in a convenient/documented way. Otherwise updating it to a new version is a pain.

**Comment by swsnr** [comment]
I'm sorry but I'll not add an uninstall target back. 

Do build your own package (and perhaps contribute it to the community), there's plenty of documentation around building packages.

Or use e.g. GNU stow to track your installation of this tool.
